apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: my-app-secret
    type: Opaque
    data:
    - objectName: "my-secret-key"
      key: secret-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: kv-dev                     # update with your actual Key Vault name
    cloudName: ""
    objects: |
      array:
        - |
          objectName: my-secret-key
          objectType: secret
    tenantId: <your-tenant-id>